// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: example.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
@kotlin.jvm.JvmName("-initializeaddress")
public inline fun address(block: AddressKt.Dsl.() -> kotlin.Unit): Example.Address =
  AddressKt.Dsl._create(Example.Address.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `Address`
 */
public object AddressKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Example.Address.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Example.Address.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Example.Address = _builder.build()

    /**
     * `string street = 1;`
     */
    public var street: kotlin.String
      @JvmName("getStreet")
      get() = _builder.getStreet()
      @JvmName("setStreet")
      set(value) {
        _builder.setStreet(value)
      }
    /**
     * `string street = 1;`
     */
    public fun clearStreet() {
      _builder.clearStreet()
    }

    /**
     * `.Address.City city = 2;`
     */
    public var city: Example.Address.City
      @JvmName("getCity")
      get() = _builder.getCity()
      @JvmName("setCity")
      set(value) {
        _builder.setCity(value)
      }
    public var cityValue: kotlin.Int
      @JvmName("getCityValue")
      get() = _builder.getCityValue()
      @JvmName("setCityValue")
      set(value) {
        _builder.setCityValue(value)
      }
    /**
     * `.Address.City city = 2;`
     */
    public fun clearCity() {
      _builder.clearCity()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Example.Address.copy(block: AddressKt.Dsl.() -> kotlin.Unit): Example.Address =
  AddressKt.Dsl._create(this.toBuilder()).apply { block() }._build()

