// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string street = 1;</code>
     * @return The street.
     */
    java.lang.String getStreet();
    /**
     * <code>string street = 1;</code>
     * @return The bytes for street.
     */
    com.google.protobuf.ByteString
        getStreetBytes();

    /**
     * <code>.Address.City city = 2;</code>
     * @return The enum numeric value on the wire for city.
     */
    int getCityValue();
    /**
     * <code>.Address.City city = 2;</code>
     * @return The city.
     */
    Example.Address.City getCity();
  }
  /**
   * Protobuf type {@code Address}
   */
  public static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      street_ = "";
      city_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Address();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Example.internal_static_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Example.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Example.Address.class, Example.Address.Builder.class);
    }

    /**
     * Protobuf enum {@code Address.City}
     */
    public enum City
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ROME = 0;</code>
       */
      ROME(0),
      /**
       * <code>BERLIN = 1;</code>
       */
      BERLIN(1),
      /**
       * <code>LONDON = 2;</code>
       */
      LONDON(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ROME = 0;</code>
       */
      public static final int ROME_VALUE = 0;
      /**
       * <code>BERLIN = 1;</code>
       */
      public static final int BERLIN_VALUE = 1;
      /**
       * <code>LONDON = 2;</code>
       */
      public static final int LONDON_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static City valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static City forNumber(int value) {
        switch (value) {
          case 0: return ROME;
          case 1: return BERLIN;
          case 2: return LONDON;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<City>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          City> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<City>() {
              public City findValueByNumber(int number) {
                return City.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Example.Address.getDescriptor().getEnumTypes().get(0);
      }

      private static final City[] VALUES = values();

      public static City valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private City(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Address.City)
    }

    public static final int STREET_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object street_ = "";
    /**
     * <code>string street = 1;</code>
     * @return The street.
     */
    @java.lang.Override
    public java.lang.String getStreet() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        street_ = s;
        return s;
      }
    }
    /**
     * <code>string street = 1;</code>
     * @return The bytes for street.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    private int city_ = 0;
    /**
     * <code>.Address.City city = 2;</code>
     * @return The enum numeric value on the wire for city.
     */
    @java.lang.Override public int getCityValue() {
      return city_;
    }
    /**
     * <code>.Address.City city = 2;</code>
     * @return The city.
     */
    @java.lang.Override public Example.Address.City getCity() {
      Example.Address.City result = Example.Address.City.forNumber(city_);
      return result == null ? Example.Address.City.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(street_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, street_);
      }
      if (city_ != Example.Address.City.ROME.getNumber()) {
        output.writeEnum(2, city_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(street_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, street_);
      }
      if (city_ != Example.Address.City.ROME.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, city_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Example.Address)) {
        return super.equals(obj);
      }
      Example.Address other = (Example.Address) obj;

      if (!getStreet()
          .equals(other.getStreet())) return false;
      if (city_ != other.city_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STREET_FIELD_NUMBER;
      hash = (53 * hash) + getStreet().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + city_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Example.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Example.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Example.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Example.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Example.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Example.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Example.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        Example.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Example.internal_static_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Example.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Example.Address.class, Example.Address.Builder.class);
      }

      // Construct using Example.Address.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        street_ = "";
        city_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Example.internal_static_Address_descriptor;
      }

      @java.lang.Override
      public Example.Address getDefaultInstanceForType() {
        return Example.Address.getDefaultInstance();
      }

      @java.lang.Override
      public Example.Address build() {
        Example.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Example.Address buildPartial() {
        Example.Address result = new Example.Address(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Example.Address result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.street_ = street_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.city_ = city_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Example.Address) {
          return mergeFrom((Example.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Example.Address other) {
        if (other == Example.Address.getDefaultInstance()) return this;
        if (!other.getStreet().isEmpty()) {
          street_ = other.street_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.city_ != 0) {
          setCityValue(other.getCityValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                street_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                city_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object street_ = "";
      /**
       * <code>string street = 1;</code>
       * @return The street.
       */
      public java.lang.String getStreet() {
        java.lang.Object ref = street_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          street_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string street = 1;</code>
       * @return The bytes for street.
       */
      public com.google.protobuf.ByteString
          getStreetBytes() {
        java.lang.Object ref = street_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          street_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string street = 1;</code>
       * @param value The street to set.
       * @return This builder for chaining.
       */
      public Builder setStreet(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        street_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string street = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreet() {
        street_ = getDefaultInstance().getStreet();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string street = 1;</code>
       * @param value The bytes for street to set.
       * @return This builder for chaining.
       */
      public Builder setStreetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        street_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int city_ = 0;
      /**
       * <code>.Address.City city = 2;</code>
       * @return The enum numeric value on the wire for city.
       */
      @java.lang.Override public int getCityValue() {
        return city_;
      }
      /**
       * <code>.Address.City city = 2;</code>
       * @param value The enum numeric value on the wire for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityValue(int value) {
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.Address.City city = 2;</code>
       * @return The city.
       */
      @java.lang.Override
      public Example.Address.City getCity() {
        Example.Address.City result = Example.Address.City.forNumber(city_);
        return result == null ? Example.Address.City.UNRECOGNIZED : result;
      }
      /**
       * <code>.Address.City city = 2;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(Example.Address.City value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        city_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Address.City city = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        city_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final Example.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Example.Address();
    }

    public static Example.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @java.lang.Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Example.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>bool married = 3;</code>
     * @return The married.
     */
    boolean getMarried();

    /**
     * <code>repeated .User friends = 4;</code>
     */
    java.util.List<Example.User> 
        getFriendsList();
    /**
     * <code>repeated .User friends = 4;</code>
     */
    Example.User getFriends(int index);
    /**
     * <code>repeated .User friends = 4;</code>
     */
    int getFriendsCount();
    /**
     * <code>repeated .User friends = 4;</code>
     */
    java.util.List<? extends Example.UserOrBuilder> 
        getFriendsOrBuilderList();
    /**
     * <code>repeated .User friends = 4;</code>
     */
    Example.UserOrBuilder getFriendsOrBuilder(
        int index);

    /**
     * <code>optional .User spouse = 5;</code>
     * @return Whether the spouse field is set.
     */
    boolean hasSpouse();
    /**
     * <code>optional .User spouse = 5;</code>
     * @return The spouse.
     */
    Example.User getSpouse();
    /**
     * <code>optional .User spouse = 5;</code>
     */
    Example.UserOrBuilder getSpouseOrBuilder();

    /**
     * <code>.Address address = 6;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <code>.Address address = 6;</code>
     * @return The address.
     */
    Example.Address getAddress();
    /**
     * <code>.Address address = 6;</code>
     */
    Example.AddressOrBuilder getAddressOrBuilder();

    /**
     * <code>string email = 7;</code>
     * @return Whether the email field is set.
     */
    boolean hasEmail();
    /**
     * <code>string email = 7;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 7;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string phone = 8;</code>
     * @return Whether the phone field is set.
     */
    boolean hasPhone();
    /**
     * <code>string phone = 8;</code>
     * @return The phone.
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 8;</code>
     * @return The bytes for phone.
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    Example.User.ContactCase getContactCase();
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      friends_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Example.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Example.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Example.User.class, Example.User.Builder.class);
    }

    private int bitField0_;
    private int contactCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object contact_;
    public enum ContactCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      EMAIL(7),
      PHONE(8),
      CONTACT_NOT_SET(0);
      private final int value;
      private ContactCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ContactCase valueOf(int value) {
        return forNumber(value);
      }

      public static ContactCase forNumber(int value) {
        switch (value) {
          case 7: return EMAIL;
          case 8: return PHONE;
          case 0: return CONTACT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ContactCase
    getContactCase() {
      return ContactCase.forNumber(
          contactCase_);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MARRIED_FIELD_NUMBER = 3;
    private boolean married_ = false;
    /**
     * <code>bool married = 3;</code>
     * @return The married.
     */
    @java.lang.Override
    public boolean getMarried() {
      return married_;
    }

    public static final int FRIENDS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<Example.User> friends_;
    /**
     * <code>repeated .User friends = 4;</code>
     */
    @java.lang.Override
    public java.util.List<Example.User> getFriendsList() {
      return friends_;
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Example.UserOrBuilder> 
        getFriendsOrBuilderList() {
      return friends_;
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    @java.lang.Override
    public int getFriendsCount() {
      return friends_.size();
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    @java.lang.Override
    public Example.User getFriends(int index) {
      return friends_.get(index);
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    @java.lang.Override
    public Example.UserOrBuilder getFriendsOrBuilder(
        int index) {
      return friends_.get(index);
    }

    public static final int SPOUSE_FIELD_NUMBER = 5;
    private Example.User spouse_;
    /**
     * <code>optional .User spouse = 5;</code>
     * @return Whether the spouse field is set.
     */
    @java.lang.Override
    public boolean hasSpouse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .User spouse = 5;</code>
     * @return The spouse.
     */
    @java.lang.Override
    public Example.User getSpouse() {
      return spouse_ == null ? Example.User.getDefaultInstance() : spouse_;
    }
    /**
     * <code>optional .User spouse = 5;</code>
     */
    @java.lang.Override
    public Example.UserOrBuilder getSpouseOrBuilder() {
      return spouse_ == null ? Example.User.getDefaultInstance() : spouse_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 6;
    private Example.Address address_;
    /**
     * <code>.Address address = 6;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.Address address = 6;</code>
     * @return The address.
     */
    @java.lang.Override
    public Example.Address getAddress() {
      return address_ == null ? Example.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>.Address address = 6;</code>
     */
    @java.lang.Override
    public Example.AddressOrBuilder getAddressOrBuilder() {
      return address_ == null ? Example.Address.getDefaultInstance() : address_;
    }

    public static final int EMAIL_FIELD_NUMBER = 7;
    /**
     * <code>string email = 7;</code>
     * @return Whether the email field is set.
     */
    public boolean hasEmail() {
      return contactCase_ == 7;
    }
    /**
     * <code>string email = 7;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = "";
      if (contactCase_ == 7) {
        ref = contact_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (contactCase_ == 7) {
          contact_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string email = 7;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = "";
      if (contactCase_ == 7) {
        ref = contact_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (contactCase_ == 7) {
          contact_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 8;
    /**
     * <code>string phone = 8;</code>
     * @return Whether the phone field is set.
     */
    public boolean hasPhone() {
      return contactCase_ == 8;
    }
    /**
     * <code>string phone = 8;</code>
     * @return The phone.
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = "";
      if (contactCase_ == 8) {
        ref = contact_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (contactCase_ == 8) {
          contact_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string phone = 8;</code>
     * @return The bytes for phone.
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = "";
      if (contactCase_ == 8) {
        ref = contact_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (contactCase_ == 8) {
          contact_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (married_ != false) {
        output.writeBool(3, married_);
      }
      for (int i = 0; i < friends_.size(); i++) {
        output.writeMessage(4, friends_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getSpouse());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(6, getAddress());
      }
      if (contactCase_ == 7) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, contact_);
      }
      if (contactCase_ == 8) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, contact_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (married_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, married_);
      }
      for (int i = 0; i < friends_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, friends_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getSpouse());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getAddress());
      }
      if (contactCase_ == 7) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, contact_);
      }
      if (contactCase_ == 8) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, contact_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Example.User)) {
        return super.equals(obj);
      }
      Example.User other = (Example.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getMarried()
          != other.getMarried()) return false;
      if (!getFriendsList()
          .equals(other.getFriendsList())) return false;
      if (hasSpouse() != other.hasSpouse()) return false;
      if (hasSpouse()) {
        if (!getSpouse()
            .equals(other.getSpouse())) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!getContactCase().equals(other.getContactCase())) return false;
      switch (contactCase_) {
        case 7:
          if (!getEmail()
              .equals(other.getEmail())) return false;
          break;
        case 8:
          if (!getPhone()
              .equals(other.getPhone())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + MARRIED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMarried());
      if (getFriendsCount() > 0) {
        hash = (37 * hash) + FRIENDS_FIELD_NUMBER;
        hash = (53 * hash) + getFriendsList().hashCode();
      }
      if (hasSpouse()) {
        hash = (37 * hash) + SPOUSE_FIELD_NUMBER;
        hash = (53 * hash) + getSpouse().hashCode();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      switch (contactCase_) {
        case 7:
          hash = (37 * hash) + EMAIL_FIELD_NUMBER;
          hash = (53 * hash) + getEmail().hashCode();
          break;
        case 8:
          hash = (37 * hash) + PHONE_FIELD_NUMBER;
          hash = (53 * hash) + getPhone().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Example.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Example.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Example.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Example.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Example.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Example.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Example.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        Example.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Example.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Example.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Example.User.class, Example.User.Builder.class);
      }

      // Construct using Example.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFriendsFieldBuilder();
          getSpouseFieldBuilder();
          getAddressFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        name_ = "";
        married_ = false;
        if (friendsBuilder_ == null) {
          friends_ = java.util.Collections.emptyList();
        } else {
          friends_ = null;
          friendsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        spouse_ = null;
        if (spouseBuilder_ != null) {
          spouseBuilder_.dispose();
          spouseBuilder_ = null;
        }
        address_ = null;
        if (addressBuilder_ != null) {
          addressBuilder_.dispose();
          addressBuilder_ = null;
        }
        contactCase_ = 0;
        contact_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Example.internal_static_User_descriptor;
      }

      @java.lang.Override
      public Example.User getDefaultInstanceForType() {
        return Example.User.getDefaultInstance();
      }

      @java.lang.Override
      public Example.User build() {
        Example.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Example.User buildPartial() {
        Example.User result = new Example.User(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Example.User result) {
        if (friendsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            friends_ = java.util.Collections.unmodifiableList(friends_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.friends_ = friends_;
        } else {
          result.friends_ = friendsBuilder_.build();
        }
      }

      private void buildPartial0(Example.User result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.married_ = married_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.spouse_ = spouseBuilder_ == null
              ? spouse_
              : spouseBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.address_ = addressBuilder_ == null
              ? address_
              : addressBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      private void buildPartialOneofs(Example.User result) {
        result.contactCase_ = contactCase_;
        result.contact_ = this.contact_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Example.User) {
          return mergeFrom((Example.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Example.User other) {
        if (other == Example.User.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getMarried() != false) {
          setMarried(other.getMarried());
        }
        if (friendsBuilder_ == null) {
          if (!other.friends_.isEmpty()) {
            if (friends_.isEmpty()) {
              friends_ = other.friends_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureFriendsIsMutable();
              friends_.addAll(other.friends_);
            }
            onChanged();
          }
        } else {
          if (!other.friends_.isEmpty()) {
            if (friendsBuilder_.isEmpty()) {
              friendsBuilder_.dispose();
              friendsBuilder_ = null;
              friends_ = other.friends_;
              bitField0_ = (bitField0_ & ~0x00000008);
              friendsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFriendsFieldBuilder() : null;
            } else {
              friendsBuilder_.addAllMessages(other.friends_);
            }
          }
        }
        if (other.hasSpouse()) {
          mergeSpouse(other.getSpouse());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        switch (other.getContactCase()) {
          case EMAIL: {
            contactCase_ = 7;
            contact_ = other.contact_;
            onChanged();
            break;
          }
          case PHONE: {
            contactCase_ = 8;
            contact_ = other.contact_;
            onChanged();
            break;
          }
          case CONTACT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                married_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                Example.User m =
                    input.readMessage(
                        Example.User.parser(),
                        extensionRegistry);
                if (friendsBuilder_ == null) {
                  ensureFriendsIsMutable();
                  friends_.add(m);
                } else {
                  friendsBuilder_.addMessage(m);
                }
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getSpouseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getAddressFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                java.lang.String s = input.readStringRequireUtf8();
                contactCase_ = 7;
                contact_ = s;
                break;
              } // case 58
              case 66: {
                java.lang.String s = input.readStringRequireUtf8();
                contactCase_ = 8;
                contact_ = s;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int contactCase_ = 0;
      private java.lang.Object contact_;
      public ContactCase
          getContactCase() {
        return ContactCase.forNumber(
            contactCase_);
      }

      public Builder clearContact() {
        contactCase_ = 0;
        contact_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private boolean married_ ;
      /**
       * <code>bool married = 3;</code>
       * @return The married.
       */
      @java.lang.Override
      public boolean getMarried() {
        return married_;
      }
      /**
       * <code>bool married = 3;</code>
       * @param value The married to set.
       * @return This builder for chaining.
       */
      public Builder setMarried(boolean value) {

        married_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool married = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMarried() {
        bitField0_ = (bitField0_ & ~0x00000004);
        married_ = false;
        onChanged();
        return this;
      }

      private java.util.List<Example.User> friends_ =
        java.util.Collections.emptyList();
      private void ensureFriendsIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          friends_ = new java.util.ArrayList<Example.User>(friends_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Example.User, Example.User.Builder, Example.UserOrBuilder> friendsBuilder_;

      /**
       * <code>repeated .User friends = 4;</code>
       */
      public java.util.List<Example.User> getFriendsList() {
        if (friendsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(friends_);
        } else {
          return friendsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public int getFriendsCount() {
        if (friendsBuilder_ == null) {
          return friends_.size();
        } else {
          return friendsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Example.User getFriends(int index) {
        if (friendsBuilder_ == null) {
          return friends_.get(index);
        } else {
          return friendsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder setFriends(
          int index, Example.User value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.set(index, value);
          onChanged();
        } else {
          friendsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder setFriends(
          int index, Example.User.Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.set(index, builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder addFriends(Example.User value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.add(value);
          onChanged();
        } else {
          friendsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder addFriends(
          int index, Example.User value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.add(index, value);
          onChanged();
        } else {
          friendsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder addFriends(
          Example.User.Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.add(builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder addFriends(
          int index, Example.User.Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.add(index, builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder addAllFriends(
          java.lang.Iterable<? extends Example.User> values) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, friends_);
          onChanged();
        } else {
          friendsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder clearFriends() {
        if (friendsBuilder_ == null) {
          friends_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          friendsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder removeFriends(int index) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.remove(index);
          onChanged();
        } else {
          friendsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Example.User.Builder getFriendsBuilder(
          int index) {
        return getFriendsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Example.UserOrBuilder getFriendsOrBuilder(
          int index) {
        if (friendsBuilder_ == null) {
          return friends_.get(index);  } else {
          return friendsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public java.util.List<? extends Example.UserOrBuilder> 
           getFriendsOrBuilderList() {
        if (friendsBuilder_ != null) {
          return friendsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(friends_);
        }
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Example.User.Builder addFriendsBuilder() {
        return getFriendsFieldBuilder().addBuilder(
            Example.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Example.User.Builder addFriendsBuilder(
          int index) {
        return getFriendsFieldBuilder().addBuilder(
            index, Example.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public java.util.List<Example.User.Builder> 
           getFriendsBuilderList() {
        return getFriendsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Example.User, Example.User.Builder, Example.UserOrBuilder> 
          getFriendsFieldBuilder() {
        if (friendsBuilder_ == null) {
          friendsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Example.User, Example.User.Builder, Example.UserOrBuilder>(
                  friends_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          friends_ = null;
        }
        return friendsBuilder_;
      }

      private Example.User spouse_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Example.User, Example.User.Builder, Example.UserOrBuilder> spouseBuilder_;
      /**
       * <code>optional .User spouse = 5;</code>
       * @return Whether the spouse field is set.
       */
      public boolean hasSpouse() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional .User spouse = 5;</code>
       * @return The spouse.
       */
      public Example.User getSpouse() {
        if (spouseBuilder_ == null) {
          return spouse_ == null ? Example.User.getDefaultInstance() : spouse_;
        } else {
          return spouseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      public Builder setSpouse(Example.User value) {
        if (spouseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          spouse_ = value;
        } else {
          spouseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      public Builder setSpouse(
          Example.User.Builder builderForValue) {
        if (spouseBuilder_ == null) {
          spouse_ = builderForValue.build();
        } else {
          spouseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      public Builder mergeSpouse(Example.User value) {
        if (spouseBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            spouse_ != null &&
            spouse_ != Example.User.getDefaultInstance()) {
            getSpouseBuilder().mergeFrom(value);
          } else {
            spouse_ = value;
          }
        } else {
          spouseBuilder_.mergeFrom(value);
        }
        if (spouse_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      public Builder clearSpouse() {
        bitField0_ = (bitField0_ & ~0x00000010);
        spouse_ = null;
        if (spouseBuilder_ != null) {
          spouseBuilder_.dispose();
          spouseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      public Example.User.Builder getSpouseBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getSpouseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      public Example.UserOrBuilder getSpouseOrBuilder() {
        if (spouseBuilder_ != null) {
          return spouseBuilder_.getMessageOrBuilder();
        } else {
          return spouse_ == null ?
              Example.User.getDefaultInstance() : spouse_;
        }
      }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Example.User, Example.User.Builder, Example.UserOrBuilder> 
          getSpouseFieldBuilder() {
        if (spouseBuilder_ == null) {
          spouseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Example.User, Example.User.Builder, Example.UserOrBuilder>(
                  getSpouse(),
                  getParentForChildren(),
                  isClean());
          spouse_ = null;
        }
        return spouseBuilder_;
      }

      private Example.Address address_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Example.Address, Example.Address.Builder, Example.AddressOrBuilder> addressBuilder_;
      /**
       * <code>.Address address = 6;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.Address address = 6;</code>
       * @return The address.
       */
      public Example.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? Example.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>.Address address = 6;</code>
       */
      public Builder setAddress(Example.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
        } else {
          addressBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.Address address = 6;</code>
       */
      public Builder setAddress(
          Example.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.Address address = 6;</code>
       */
      public Builder mergeAddress(Example.Address value) {
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            address_ != null &&
            address_ != Example.Address.getDefaultInstance()) {
            getAddressBuilder().mergeFrom(value);
          } else {
            address_ = value;
          }
        } else {
          addressBuilder_.mergeFrom(value);
        }
        if (address_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.Address address = 6;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000020);
        address_ = null;
        if (addressBuilder_ != null) {
          addressBuilder_.dispose();
          addressBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Address address = 6;</code>
       */
      public Example.Address.Builder getAddressBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>.Address address = 6;</code>
       */
      public Example.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              Example.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>.Address address = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Example.Address, Example.Address.Builder, Example.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Example.Address, Example.Address.Builder, Example.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }

      /**
       * <code>string email = 7;</code>
       * @return Whether the email field is set.
       */
      @java.lang.Override
      public boolean hasEmail() {
        return contactCase_ == 7;
      }
      /**
       * <code>string email = 7;</code>
       * @return The email.
       */
      @java.lang.Override
      public java.lang.String getEmail() {
        java.lang.Object ref = "";
        if (contactCase_ == 7) {
          ref = contact_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (contactCase_ == 7) {
            contact_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 7;</code>
       * @return The bytes for email.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = "";
        if (contactCase_ == 7) {
          ref = contact_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (contactCase_ == 7) {
            contact_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 7;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contactCase_ = 7;
        contact_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        if (contactCase_ == 7) {
          contactCase_ = 0;
          contact_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string email = 7;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contactCase_ = 7;
        contact_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string phone = 8;</code>
       * @return Whether the phone field is set.
       */
      @java.lang.Override
      public boolean hasPhone() {
        return contactCase_ == 8;
      }
      /**
       * <code>string phone = 8;</code>
       * @return The phone.
       */
      @java.lang.Override
      public java.lang.String getPhone() {
        java.lang.Object ref = "";
        if (contactCase_ == 8) {
          ref = contact_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (contactCase_ == 8) {
            contact_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone = 8;</code>
       * @return The bytes for phone.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = "";
        if (contactCase_ == 8) {
          ref = contact_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (contactCase_ == 8) {
            contact_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 8;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contactCase_ = 8;
        contact_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        if (contactCase_ == 8) {
          contactCase_ = 0;
          contact_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string phone = 8;</code>
       * @param value The bytes for phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contactCase_ = 8;
        contact_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final Example.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Example.User();
    }

    public static Example.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Example.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\"`\n\007Address\022\016\n\006street\030\001 \001" +
      "(\t\022\033\n\004city\030\002 \001(\0162\r.Address.City\"(\n\004City\022" +
      "\010\n\004ROME\020\000\022\n\n\006BERLIN\020\001\022\n\n\006LONDON\020\002\"\270\001\n\004Us" +
      "er\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\017\n\007married\030" +
      "\003 \001(\010\022\026\n\007friends\030\004 \003(\0132\005.User\022\032\n\006spouse\030" +
      "\005 \001(\0132\005.UserH\001\210\001\001\022\031\n\007address\030\006 \001(\0132\010.Add" +
      "ress\022\017\n\005email\030\007 \001(\tH\000\022\017\n\005phone\030\010 \001(\tH\000B\t" +
      "\n\007contactB\t\n\007_spouseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "Street", "City", });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Married", "Friends", "Spouse", "Address", "Email", "Phone", "Contact", "Spouse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
