// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string street = 1;</code>
     * @return The street.
     */
    java.lang.String getStreet();
    /**
     * <code>string street = 1;</code>
     * @return The bytes for street.
     */
    com.google.protobuf.ByteString
        getStreetBytes();

    /**
     * <code>.Address.City city = 2;</code>
     * @return The enum numeric value on the wire for city.
     */
    int getCityValue();
    /**
     * <code>.Address.City city = 2;</code>
     * @return The city.
     */
    Example.Address.City getCity();
  }
  /**
   * Protobuf type {@code Address}
   */
  public  static final class Address extends
      com.google.protobuf.GeneratedMessageLite<
          Address, Address.Builder> implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
    private Address() {
      street_ = "";
    }
    /**
     * Protobuf enum {@code Address.City}
     */
    public enum City
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>ROME = 0;</code>
       */
      ROME(0),
      /**
       * <code>BERLIN = 1;</code>
       */
      BERLIN(1),
      /**
       * <code>LONDON = 2;</code>
       */
      LONDON(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ROME = 0;</code>
       */
      public static final int ROME_VALUE = 0;
      /**
       * <code>BERLIN = 1;</code>
       */
      public static final int BERLIN_VALUE = 1;
      /**
       * <code>LONDON = 2;</code>
       */
      public static final int LONDON_VALUE = 2;


      @java.lang.Override
      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static City valueOf(int value) {
        return forNumber(value);
      }

      public static City forNumber(int value) {
        switch (value) {
          case 0: return ROME;
          case 1: return BERLIN;
          case 2: return LONDON;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<City>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          City> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<City>() {
              @java.lang.Override
              public City findValueByNumber(int number) {
                return City.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return CityVerifier.INSTANCE;
      }

      private static final class CityVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new CityVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return City.forNumber(number) != null;
              }
            };

      private final int value;

      private City(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Address.City)
    }

    public static final int STREET_FIELD_NUMBER = 1;
    private java.lang.String street_;
    /**
     * <code>string street = 1;</code>
     * @return The street.
     */
    @java.lang.Override
    public java.lang.String getStreet() {
      return street_;
    }
    /**
     * <code>string street = 1;</code>
     * @return The bytes for street.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreetBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(street_);
    }
    /**
     * <code>string street = 1;</code>
     * @param value The street to set.
     */
    private void setStreet(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      street_ = value;
    }
    /**
     * <code>string street = 1;</code>
     */
    private void clearStreet() {

      street_ = getDefaultInstance().getStreet();
    }
    /**
     * <code>string street = 1;</code>
     * @param value The bytes for street to set.
     */
    private void setStreetBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      street_ = value.toStringUtf8();

    }

    public static final int CITY_FIELD_NUMBER = 2;
    private int city_;
    /**
     * <code>.Address.City city = 2;</code>
     * @return The enum numeric value on the wire for city.
     */
    @java.lang.Override
    public int getCityValue() {
      return city_;
    }
    /**
     * <code>.Address.City city = 2;</code>
     * @return The city.
     */
    @java.lang.Override
    public Example.Address.City getCity() {
      Example.Address.City result = Example.Address.City.forNumber(city_);
      return result == null ? Example.Address.City.UNRECOGNIZED : result;
    }
    /**
     * <code>.Address.City city = 2;</code>
     * @param value The enum numeric value on the wire for city to set.
     */
    private void setCityValue(int value) {
        city_ = value;
    }
    /**
     * <code>.Address.City city = 2;</code>
     * @param value The city to set.
     */
    private void setCity(Example.Address.City value) {
      city_ = value.getNumber();

    }
    /**
     * <code>.Address.City city = 2;</code>
     */
    private void clearCity() {

      city_ = 0;
    }

    public static Example.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Example.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Example.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Example.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Example.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Example.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Example.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Example.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Example.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static Example.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Example.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Example.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Example.Address prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Example.Address, Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        Example.AddressOrBuilder {
      // Construct using Example.Address.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string street = 1;</code>
       * @return The street.
       */
      @java.lang.Override
      public java.lang.String getStreet() {
        return instance.getStreet();
      }
      /**
       * <code>string street = 1;</code>
       * @return The bytes for street.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStreetBytes() {
        return instance.getStreetBytes();
      }
      /**
       * <code>string street = 1;</code>
       * @param value The street to set.
       * @return This builder for chaining.
       */
      public Builder setStreet(
          java.lang.String value) {
        copyOnWrite();
        instance.setStreet(value);
        return this;
      }
      /**
       * <code>string street = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreet() {
        copyOnWrite();
        instance.clearStreet();
        return this;
      }
      /**
       * <code>string street = 1;</code>
       * @param value The bytes for street to set.
       * @return This builder for chaining.
       */
      public Builder setStreetBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStreetBytes(value);
        return this;
      }

      /**
       * <code>.Address.City city = 2;</code>
       * @return The enum numeric value on the wire for city.
       */
      @java.lang.Override
      public int getCityValue() {
        return instance.getCityValue();
      }
      /**
       * <code>.Address.City city = 2;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCityValue(int value) {
        copyOnWrite();
        instance.setCityValue(value);
        return this;
      }
      /**
       * <code>.Address.City city = 2;</code>
       * @return The city.
       */
      @java.lang.Override
      public Example.Address.City getCity() {
        return instance.getCity();
      }
      /**
       * <code>.Address.City city = 2;</code>
       * @param value The enum numeric value on the wire for city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(Example.Address.City value) {
        copyOnWrite();
        instance.setCity(value);
        return this;
      }
      /**
       * <code>.Address.City city = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        copyOnWrite();
        instance.clearCity();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Address)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Example.Address();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "street_",
              "city_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\f" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Example.Address> parser = PARSER;
          if (parser == null) {
            synchronized (Example.Address.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Example.Address>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Address)
    private static final Example.Address DEFAULT_INSTANCE;
    static {
      Address defaultInstance = new Address();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Address.class, defaultInstance);
    }

    public static Example.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Address> PARSER;

    public static com.google.protobuf.Parser<Address> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>bool married = 3;</code>
     * @return The married.
     */
    boolean getMarried();

    /**
     * <code>repeated .User friends = 4;</code>
     */
    java.util.List<Example.User> 
        getFriendsList();
    /**
     * <code>repeated .User friends = 4;</code>
     */
    Example.User getFriends(int index);
    /**
     * <code>repeated .User friends = 4;</code>
     */
    int getFriendsCount();

    /**
     * <code>optional .User spouse = 5;</code>
     * @return Whether the spouse field is set.
     */
    boolean hasSpouse();
    /**
     * <code>optional .User spouse = 5;</code>
     * @return The spouse.
     */
    Example.User getSpouse();

    /**
     * <code>.Address address = 6;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <code>.Address address = 6;</code>
     * @return The address.
     */
    Example.Address getAddress();

    /**
     * <code>string email = 7;</code>
     * @return Whether the email field is set.
     */
    boolean hasEmail();
    /**
     * <code>string email = 7;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 7;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string phone = 8;</code>
     * @return Whether the phone field is set.
     */
    boolean hasPhone();
    /**
     * <code>string phone = 8;</code>
     * @return The phone.
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 8;</code>
     * @return The bytes for phone.
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    public Example.User.ContactCase getContactCase();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageLite<
          User, User.Builder> implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
    private User() {
      name_ = "";
      friends_ = emptyProtobufList();
    }
    private int bitField0_;
    private int contactCase_ = 0;
    private java.lang.Object contact_;
    public enum ContactCase {
      EMAIL(7),
      PHONE(8),
      CONTACT_NOT_SET(0);
      private final int value;
      private ContactCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ContactCase valueOf(int value) {
        return forNumber(value);
      }

      public static ContactCase forNumber(int value) {
        switch (value) {
          case 7: return EMAIL;
          case 8: return PHONE;
          case 0: return CONTACT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @java.lang.Override
    public ContactCase
    getContactCase() {
      return ContactCase.forNumber(
          contactCase_);
    }

    private void clearContact() {
      contactCase_ = 0;
      contact_ = null;
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     */
    private void setId(long value) {
      
      id_ = value;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    private void clearId() {

      id_ = 0L;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.String name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      name_ = value;
    }
    /**
     * <code>string name = 2;</code>
     */
    private void clearName() {

      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();

    }

    public static final int MARRIED_FIELD_NUMBER = 3;
    private boolean married_;
    /**
     * <code>bool married = 3;</code>
     * @return The married.
     */
    @java.lang.Override
    public boolean getMarried() {
      return married_;
    }
    /**
     * <code>bool married = 3;</code>
     * @param value The married to set.
     */
    private void setMarried(boolean value) {
      
      married_ = value;
    }
    /**
     * <code>bool married = 3;</code>
     */
    private void clearMarried() {

      married_ = false;
    }

    public static final int FRIENDS_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<Example.User> friends_;
    /**
     * <code>repeated .User friends = 4;</code>
     */
    @java.lang.Override
    public java.util.List<Example.User> getFriendsList() {
      return friends_;
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    public java.util.List<? extends Example.UserOrBuilder> 
        getFriendsOrBuilderList() {
      return friends_;
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    @java.lang.Override
    public int getFriendsCount() {
      return friends_.size();
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    @java.lang.Override
    public Example.User getFriends(int index) {
      return friends_.get(index);
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    public Example.UserOrBuilder getFriendsOrBuilder(
        int index) {
      return friends_.get(index);
    }
    private void ensureFriendsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<Example.User> tmp = friends_;
      if (!tmp.isModifiable()) {
        friends_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .User friends = 4;</code>
     */
    private void setFriends(
        int index, Example.User value) {
      value.getClass();
  ensureFriendsIsMutable();
      friends_.set(index, value);
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    private void addFriends(Example.User value) {
      value.getClass();
  ensureFriendsIsMutable();
      friends_.add(value);
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    private void addFriends(
        int index, Example.User value) {
      value.getClass();
  ensureFriendsIsMutable();
      friends_.add(index, value);
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    private void addAllFriends(
        java.lang.Iterable<? extends Example.User> values) {
      ensureFriendsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, friends_);
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    private void clearFriends() {
      friends_ = emptyProtobufList();
    }
    /**
     * <code>repeated .User friends = 4;</code>
     */
    private void removeFriends(int index) {
      ensureFriendsIsMutable();
      friends_.remove(index);
    }

    public static final int SPOUSE_FIELD_NUMBER = 5;
    private Example.User spouse_;
    /**
     * <code>optional .User spouse = 5;</code>
     */
    @java.lang.Override
    public boolean hasSpouse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .User spouse = 5;</code>
     */
    @java.lang.Override
    public Example.User getSpouse() {
      return spouse_ == null ? Example.User.getDefaultInstance() : spouse_;
    }
    /**
     * <code>optional .User spouse = 5;</code>
     */
    private void setSpouse(Example.User value) {
      value.getClass();
  spouse_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>optional .User spouse = 5;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeSpouse(Example.User value) {
      value.getClass();
  if (spouse_ != null &&
          spouse_ != Example.User.getDefaultInstance()) {
        spouse_ =
          Example.User.newBuilder(spouse_).mergeFrom(value).buildPartial();
      } else {
        spouse_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>optional .User spouse = 5;</code>
     */
    private void clearSpouse() {  spouse_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int ADDRESS_FIELD_NUMBER = 6;
    private Example.Address address_;
    /**
     * <code>.Address address = 6;</code>
     */
    @java.lang.Override
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.Address address = 6;</code>
     */
    @java.lang.Override
    public Example.Address getAddress() {
      return address_ == null ? Example.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>.Address address = 6;</code>
     */
    private void setAddress(Example.Address value) {
      value.getClass();
  address_ = value;
      bitField0_ |= 0x00000002;
      }
    /**
     * <code>.Address address = 6;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeAddress(Example.Address value) {
      value.getClass();
  if (address_ != null &&
          address_ != Example.Address.getDefaultInstance()) {
        address_ =
          Example.Address.newBuilder(address_).mergeFrom(value).buildPartial();
      } else {
        address_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>.Address address = 6;</code>
     */
    private void clearAddress() {  address_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public static final int EMAIL_FIELD_NUMBER = 7;
    /**
     * <code>string email = 7;</code>
     * @return Whether the email field is set.
     */
    @java.lang.Override
    public boolean hasEmail() {
      return contactCase_ == 7;
    }
    /**
     * <code>string email = 7;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.String ref = "";
      if (contactCase_ == 7) {
        ref = (java.lang.String) contact_;
      }
      return ref;
    }
    /**
     * <code>string email = 7;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.String ref = "";
      if (contactCase_ == 7) {
        ref = (java.lang.String) contact_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <code>string email = 7;</code>
     * @param value The email to set.
     */
    private void setEmail(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  contactCase_ = 7;
      contact_ = value;
    }
    /**
     * <code>string email = 7;</code>
     */
    private void clearEmail() {
      if (contactCase_ == 7) {
        contactCase_ = 0;
        contact_ = null;
      }
    }
    /**
     * <code>string email = 7;</code>
     * @param value The bytes for email to set.
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      contact_ = value.toStringUtf8();
      contactCase_ = 7;
    }

    public static final int PHONE_FIELD_NUMBER = 8;
    /**
     * <code>string phone = 8;</code>
     * @return Whether the phone field is set.
     */
    @java.lang.Override
    public boolean hasPhone() {
      return contactCase_ == 8;
    }
    /**
     * <code>string phone = 8;</code>
     * @return The phone.
     */
    @java.lang.Override
    public java.lang.String getPhone() {
      java.lang.String ref = "";
      if (contactCase_ == 8) {
        ref = (java.lang.String) contact_;
      }
      return ref;
    }
    /**
     * <code>string phone = 8;</code>
     * @return The bytes for phone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.String ref = "";
      if (contactCase_ == 8) {
        ref = (java.lang.String) contact_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <code>string phone = 8;</code>
     * @param value The phone to set.
     */
    private void setPhone(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  contactCase_ = 8;
      contact_ = value;
    }
    /**
     * <code>string phone = 8;</code>
     */
    private void clearPhone() {
      if (contactCase_ == 8) {
        contactCase_ = 0;
        contact_ = null;
      }
    }
    /**
     * <code>string phone = 8;</code>
     * @param value The bytes for phone to set.
     */
    private void setPhoneBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      contact_ = value.toStringUtf8();
      contactCase_ = 8;
    }

    public static Example.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Example.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Example.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Example.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Example.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Example.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Example.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Example.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Example.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static Example.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Example.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Example.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Example.User prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Example.User, Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        Example.UserOrBuilder {
      // Construct using Example.User.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public ContactCase
          getContactCase() {
        return instance.getContactCase();
      }

      public Builder clearContact() {
        copyOnWrite();
        instance.clearContact();
        return this;
      }


      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return instance.getId();
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>bool married = 3;</code>
       * @return The married.
       */
      @java.lang.Override
      public boolean getMarried() {
        return instance.getMarried();
      }
      /**
       * <code>bool married = 3;</code>
       * @param value The married to set.
       * @return This builder for chaining.
       */
      public Builder setMarried(boolean value) {
        copyOnWrite();
        instance.setMarried(value);
        return this;
      }
      /**
       * <code>bool married = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMarried() {
        copyOnWrite();
        instance.clearMarried();
        return this;
      }

      /**
       * <code>repeated .User friends = 4;</code>
       */
      @java.lang.Override
      public java.util.List<Example.User> getFriendsList() {
        return java.util.Collections.unmodifiableList(
            instance.getFriendsList());
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      @java.lang.Override
      public int getFriendsCount() {
        return instance.getFriendsCount();
      }/**
       * <code>repeated .User friends = 4;</code>
       */
      @java.lang.Override
      public Example.User getFriends(int index) {
        return instance.getFriends(index);
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder setFriends(
          int index, Example.User value) {
        copyOnWrite();
        instance.setFriends(index, value);
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder setFriends(
          int index, Example.User.Builder builderForValue) {
        copyOnWrite();
        instance.setFriends(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder addFriends(Example.User value) {
        copyOnWrite();
        instance.addFriends(value);
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder addFriends(
          int index, Example.User value) {
        copyOnWrite();
        instance.addFriends(index, value);
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder addFriends(
          Example.User.Builder builderForValue) {
        copyOnWrite();
        instance.addFriends(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder addFriends(
          int index, Example.User.Builder builderForValue) {
        copyOnWrite();
        instance.addFriends(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder addAllFriends(
          java.lang.Iterable<? extends Example.User> values) {
        copyOnWrite();
        instance.addAllFriends(values);
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder clearFriends() {
        copyOnWrite();
        instance.clearFriends();
        return this;
      }
      /**
       * <code>repeated .User friends = 4;</code>
       */
      public Builder removeFriends(int index) {
        copyOnWrite();
        instance.removeFriends(index);
        return this;
      }

      /**
       * <code>optional .User spouse = 5;</code>
       */
      @java.lang.Override
      public boolean hasSpouse() {
        return instance.hasSpouse();
      }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      @java.lang.Override
      public Example.User getSpouse() {
        return instance.getSpouse();
      }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      public Builder setSpouse(Example.User value) {
        copyOnWrite();
        instance.setSpouse(value);
        return this;
        }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      public Builder setSpouse(
          Example.User.Builder builderForValue) {
        copyOnWrite();
        instance.setSpouse(builderForValue.build());
        return this;
      }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      public Builder mergeSpouse(Example.User value) {
        copyOnWrite();
        instance.mergeSpouse(value);
        return this;
      }
      /**
       * <code>optional .User spouse = 5;</code>
       */
      public Builder clearSpouse() {  copyOnWrite();
        instance.clearSpouse();
        return this;
      }

      /**
       * <code>.Address address = 6;</code>
       */
      @java.lang.Override
      public boolean hasAddress() {
        return instance.hasAddress();
      }
      /**
       * <code>.Address address = 6;</code>
       */
      @java.lang.Override
      public Example.Address getAddress() {
        return instance.getAddress();
      }
      /**
       * <code>.Address address = 6;</code>
       */
      public Builder setAddress(Example.Address value) {
        copyOnWrite();
        instance.setAddress(value);
        return this;
        }
      /**
       * <code>.Address address = 6;</code>
       */
      public Builder setAddress(
          Example.Address.Builder builderForValue) {
        copyOnWrite();
        instance.setAddress(builderForValue.build());
        return this;
      }
      /**
       * <code>.Address address = 6;</code>
       */
      public Builder mergeAddress(Example.Address value) {
        copyOnWrite();
        instance.mergeAddress(value);
        return this;
      }
      /**
       * <code>.Address address = 6;</code>
       */
      public Builder clearAddress() {  copyOnWrite();
        instance.clearAddress();
        return this;
      }

      /**
       * <code>string email = 7;</code>
       * @return Whether the email field is set.
       */
      @java.lang.Override
      public boolean hasEmail() {
        return instance.hasEmail();
      }
      /**
       * <code>string email = 7;</code>
       * @return The email.
       */
      @java.lang.Override
      public java.lang.String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>string email = 7;</code>
       * @return The bytes for email.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>string email = 7;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>string email = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>string email = 7;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>string phone = 8;</code>
       * @return Whether the phone field is set.
       */
      @java.lang.Override
      public boolean hasPhone() {
        return instance.hasPhone();
      }
      /**
       * <code>string phone = 8;</code>
       * @return The phone.
       */
      @java.lang.Override
      public java.lang.String getPhone() {
        return instance.getPhone();
      }
      /**
       * <code>string phone = 8;</code>
       * @return The bytes for phone.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        return instance.getPhoneBytes();
      }
      /**
       * <code>string phone = 8;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          java.lang.String value) {
        copyOnWrite();
        instance.setPhone(value);
        return this;
      }
      /**
       * <code>string phone = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        copyOnWrite();
        instance.clearPhone();
        return this;
      }
      /**
       * <code>string phone = 8;</code>
       * @param value The bytes for phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPhoneBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:User)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Example.User();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "contact_",
              "contactCase_",
              "bitField0_",
              "id_",
              "name_",
              "married_",
              "friends_",
              Example.User.class,
              "spouse_",
              "address_",
            };
            java.lang.String info =
                "\u0000\b\u0001\u0001\u0001\b\b\u0000\u0001\u0000\u0001\u0002\u0002\u0208\u0003\u0007" +
                "\u0004\u001b\u0005\u1009\u0000\u0006\u1009\u0001\u0007\u023b\u0000\b\u023b\u0000" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Example.User> parser = PARSER;
          if (parser == null) {
            synchronized (Example.User.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Example.User>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:User)
    private static final Example.User DEFAULT_INSTANCE;
    static {
      User defaultInstance = new User();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        User.class, defaultInstance);
    }

    public static Example.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<User> PARSER;

    public static com.google.protobuf.Parser<User> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
